#!/bin/bash
"exec" "`dirname $0`/venv/bin/python" "$0" "$@"

import sys
import serial

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

SCREEN_WIDTH = 128
SCREEN_HEIGHT = 64

class Worker(QThread):
    screen = pyqtSignal(bytes)
    def run(self):
        ser = serial.Serial(sys.argv[1])
        ser.write(b"screen_stream\r")
        while True:
            ser.read_until(bytes.fromhex('F0E1D2C3'))
            data = ser.read(1024)
            self.screen.emit(data)

class Screen(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.resize(SCREEN_WIDTH * 2, SCREEN_HEIGHT * 2)
        self.canvas = QImage(128, 64, QImage.Format_Mono)
        self.canvas.fill(1)

        p = QPainter()
        p.begin(self.canvas)
        p.drawText(self.canvas.rect(), Qt.AlignCenter, "Connecting");
        p.end();

        self.adjusted_to_size = (-1, -1)
        self.ratio = 2/1
        self.setSizePolicy(QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored))

        self.worker = Worker(self)
        self.worker.screen.connect(self.data)
        self.worker.setTerminationEnabled(True)
        self.worker.start()

    def paintEvent(self, event):
        qp = QPainter()
        qp.begin(self)
        qp.drawImage(self.rect(), self.canvas)
        qp.end()

    def resizeEvent(self, event):
        size = event.size()
        if size == self.adjusted_to_size:
            # Avoid infinite recursion. I suspect Qt does this for you,
            # but it's best to be safe.
            return
        self.adjusted_to_size = size

        full_width = size.width()
        full_height = size.height()

        width = int(min(full_width, full_height * self.ratio))
        height = int(min(full_height, full_width / self.ratio))

        self.resize(width, height)

    def closeEvent(self, evnt):
        self.worker.terminate()

    def isPixelSet(self, frame, x:int, y:int):
        i = int(y / 8) * 128
        y &= 7
        i = int(i + x)
        return (frame[i] & (1 << y)) == 0

    @pyqtSlot(bytes)
    def data(self, data):
        for y in range(SCREEN_HEIGHT):
            for x in range(SCREEN_WIDTH):
                color = self.isPixelSet(data, x, y)
                self.canvas.setPixel(x, y, color)
        self.update()

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Path to serial is required")
        exit(255)
    app = QApplication(sys.argv)
    widget = Screen()
    widget.show()
    app.exec_()
